### ISSUE TITLE
wrapper.apply error

### ISSUE THREAD

**Issue by matteo-cristino** [uNetworking/uWebSockets.js#1053]
We are using your uWebSocket package in out application called [ncr](https://github.com/forkbombEu/ncr), from which we create a binary file and we use it also in our github actions.

Randomly I get the following errors
```
pkg/prelude/bootstrap.js:1926
      return wrapper.apply(this.exports, args);
                     ^

Error: This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

Error: EEXIST: file already exists, mkdir '/tmp/pkg/8587103d6a12b0e5ed732a11cbaf94ec2a6f7b899f3d72c40c577accb5a41d1b'
    at /snapshot/ncr/dist/index.cjs
    at Object.<anonymous> (/snapshot/ncr/dist/index.cjs)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.5.0
```

```
pkg/prelude/bootstrap.js:1926
      return wrapper.apply(this.exports, args);
                     ^

Error: This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

Error: /tmp/pkg/8587103d6a12b0e5ed732a11cbaf94ec2a6f7b899f3d72c40c577accb5a41d1b/uws_linux_x64_108.node: file too short
    at /snapshot/ncr/dist/index.cjs
    at Object.<anonymous> (/snapshot/ncr/dist/index.cjs)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.5.0
```

Maybe can be some concurrency issue, at the moment we are running 6 app that use uwebsocket on six different ports on the same machine.

**Comment by uNetworkingAB** [comment]
You have posted 2 file errors. So report it to whatever project messes with files. It's not an issue to report here.
