### ISSUE TITLE
Segmentation fault (core dumped)  when listen to https using example WorkerThreads.js

### ISSUE THREAD

**Issue by snowinszu** [uNetworking/uWebSockets.js#1119]
code like this:
```
if (isMainThread) {

	/* The acceptorApp only listens, but must be SSL if worker apps are SSL and likewise opposite */
	const acceptorApp = uWS.SSLApp({
		key_file_name: 'misc/key.pem',
		cert_file_name: 'misc/cert.pem',
		passphrase: '1234'
	  }).listen(port, (token) => {
		if (token) {
		  console.log('Listening to port ' + port + ' from thread ' + threadId + ' as main acceptor');
		} else {
		  console.log('Failed to listen to port ' + port + ' from thread ' + threadId);
		}
	  });

  /* Main thread loops over all CPUs */
  /* In this case we only spawn two (hardcoded) */
  /*os.cpus()*/[0, 1].forEach(() => {
	
    /* Spawn a new thread running this source file */
    new Worker(__filename).on("message", (workerAppDescriptor) => {
		acceptorApp.addChildAppDescriptor(workerAppDescriptor);
	});
  });

  /* I guess main thread joins by default? */
} else {
  /* Here we are inside a worker thread */
  const app = uWS.SSLApp({
    key_file_name: 'misc/key.pem',
    cert_file_name: 'misc/cert.pem',
    passphrase: '1234'
  }).get('/*', (res, req) => {
    res.end('Hello Worker!');
  }).listen(4000, (token) => {
	if (token) {
		console.log('Listening to port ' + 4000 + ' from thread ' + threadId);
	  } else {
		console.log('Failed to listen to port ' + 4000 + ' from thread ' + threadId);
	  }
  });

  /* The worker sends back its descriptor to the main acceptor */
  parentPort.postMessage(app.getDescriptor());
}
```

Testing on ubuntu 24.04

**Comment by christian-bromann** [comment]
I was also not able to get the worker thread example working. I used the following script:
```js
import uWS from 'uWebSockets.js'
import { Worker, isMainThread, threadId, parentPort } from 'node:worker_threads'

const port = 9001
const __filename = new URL(import.meta.url).pathname

if (isMainThread) {
  const acceptorApp = uWS.App()
  acceptorApp.listen(port, (token) => {
    if (token) {
      console.log('Listening to port ' + port + ' from thread ' + threadId + ' as main acceptor')
    } else {
      console.log('Failed to listen to port ' + port + ' from thread ' + threadId)
    }
  })

  const threads = [0, 1]
  threads.forEach(() => {

    /* Spawn a new thread running this source file */
    new Worker(__filename).on('message', (workerAppDescriptor) => {
      acceptorApp.addChildAppDescriptor(workerAppDescriptor)
    })
  })

  /* I guess main thread joins by default? */
} else {
  /* Here we are inside a worker thread */
  const app = uWS.App().get('/*', (res, req) => {
    res.end('Hello Worker!')
  }).listen(4000, (token) => {
    if (token) {
      console.log('Listening to port ' + 4000 + ' from thread ' + threadId)
    } else {
      console.log('Failed to listen to port ' + 4000 + ' from thread ' + threadId)
    }
  })

  /* The worker sends back its descriptor to the main acceptor */
  parentPort?.postMessage(app.workerAppDescriptor)
}
```

There is no function called `getDescriptor` nor `workerAppDescriptor` property. Any feedback how to achieve this?

**Comment by uNetworkingAB** [comment]
Yes there is a segfault if your listener is not SSL but your worker is, here is ASAN example:

```
=================================================================
==28036==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x51200004d9e4 at pc 0x7a5731d2db64 bp 0x7a5730cf03b0 sp 0x7a5730cf03a0
WRITE of size 1 at 0x51200004d9e4 thread T8
    #0 0x7a5731d2db63 in uWS::ProxyParser::ProxyParser() uWebSockets/src/ProxyParser.h:74
    #1 0x7a5731d2db63 in uWS::HttpResponseData<true>::HttpResponseData() uWebSockets/src/HttpResponseData.h:32
    #2 0x7a5731d2db63 in uWS::HttpContext<true>::init()::{lambda(us_socket_t*, int, char*, int)#1}::operator()(us_socket_t*, int, char*, int) const uWebSockets/src/HttpContext.h:77
    #3 0x7a5731d2db63 in uWS::HttpContext<true>::init()::{lambda(us_socket_t*, int, char*, int)#1}::__invoke(us_socket_t*, int, char*, int) uWebSockets/src/HttpContext.h:72
    #4 0x7a5731d62da0 in us_adopt_accepted_socket /home/runner/work/uWebSockets.js/uWebSockets.js/uWebSockets.js/uWebSockets/uSockets/src/loop.c:221
    #5 0x7a5731c97631 in ofats::any_detail::any_invocable_impl<void, false>::call() uWebSockets/src/MoveOnlyFunction.h:250
    #6 0x7a5731c97631 in ofats::any_invocable<void ()>::operator()() uWebSockets/src/MoveOnlyFunction.h:357
    #7 0x7a5731c97631 in uWS::Loop::wakeupCb(us_loop_t*) uWebSockets/src/Loop.h:50
    #8 0x210d4c2 in uv__async_io ../deps/uv/src/unix/async.c:208
    #9 0x2123f69 in uv__io_poll ../deps/uv/src/unix/linux.c:1565
    #10 0x210e186 in uv_run ../deps/uv/src/unix/core.c:460
    #11 0xf8c054 in node::SpinEventLoopInternal(node::Environment*) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0xf8c054) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #12 0x1228856 in node::worker::Worker::Run() (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1228856) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #13 0x12289c5 in node::worker::Worker::StartThread(v8::FunctionCallbackInfo<v8::Value> const&)::{lambda(void*)#1}::_FUN(void*) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x12289c5) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #14 0x7a5773e5ea41 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #15 0x7a577369caa3 in start_thread nptl/pthread_create.c:447
    #16 0x7a5773729c6b in clone3 ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

0x51200004d9e4 is located 12 bytes after 280-byte region [0x51200004d8c0,0x51200004d9d8)
allocated by thread T8 here:
    #0 0x7a5773efd9c7 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7a5731d61b90 in us_create_poll /home/runner/work/uWebSockets.js/uWebSockets.js/uWebSockets.js/uWebSockets/uSockets/src/eventing/libuv.c:196
    #2 0x7a5731d62cc3 in us_adopt_accepted_socket /home/runner/work/uWebSockets.js/uWebSockets.js/uWebSockets.js/uWebSockets/uSockets/src/loop.c:205
    #3 0x7a5731c97631 in ofats::any_detail::any_invocable_impl<void, false>::call() uWebSockets/src/MoveOnlyFunction.h:250
    #4 0x7a5731c97631 in ofats::any_invocable<void ()>::operator()() uWebSockets/src/MoveOnlyFunction.h:357
    #5 0x7a5731c97631 in uWS::Loop::wakeupCb(us_loop_t*) uWebSockets/src/Loop.h:50
    #6 0x210d4c2 in uv__async_io ../deps/uv/src/unix/async.c:208
    #7 0x2123f69 in uv__io_poll ../deps/uv/src/unix/linux.c:1565
    #8 0x210e186 in uv_run ../deps/uv/src/unix/core.c:460
    #9 0xf8c054 in node::SpinEventLoopInternal(node::Environment*) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0xf8c054) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #10 0x1228856 in node::worker::Worker::Run() (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1228856) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #11 0x12289c5 in node::worker::Worker::StartThread(v8::FunctionCallbackInfo<v8::Value> const&)::{lambda(void*)#1}::_FUN(void*) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x12289c5) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #12 0x7a5773e5ea41 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #13 0x7a577369caa3 in start_thread nptl/pthread_create.c:447

Thread T8 created by T0 here:
    #0 0x7a5773ef51f9 in pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:245
    #1 0x211d161 in uv_thread_create_ex ../deps/uv/src/unix/thread.c:181
    #2 0x1222e3b in node::worker::Worker::StartThread(v8::FunctionCallbackInfo<v8::Value> const&) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1222e3b) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #3 0x7a575254f08c  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d3708c)
    #4 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #5 0x7a575254ddce  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35dce)
    #6 0x7a5752701100  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1ee9100)
    #7 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #8 0x7a5752616cae  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1dfecae)
    #9 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #10 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #11 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #12 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #13 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #14 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #15 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #16 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #17 0x7a575254d653  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d35653)
    #18 0x7a575254b21b  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d3321b)
    #19 0x7a575254af66  (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1d32f66)
    #20 0x1531b60 in v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1531b60) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #21 0x1532a0e in v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::DirectHandle<v8::internal::Object>, v8::internal::DirectHandle<v8::internal::Object>, v8::base::Vector<v8::internal::DirectHandle<v8::internal::Object> const>) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1532a0e) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #22 0x139f806 in v8::Function::Call(v8::Isolate*, v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x139f806) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #23 0x1084292 in node::builtins::BuiltinLoader::CompileAndCall(v8::Local<v8::Context>, char const*, node::Realm*) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1084292) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #24 0x11779a2 in node::Realm::ExecuteBootstrapper(char const*) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x11779a2) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #25 0x10501ff in node::StartExecution(node::Environment*, char const*) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x10501ff) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #26 0x1059331 in node::StartExecution(node::Environment*, std::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1059331) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #27 0xf8fd43 in node::LoadEnvironment(node::Environment*, std::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>, std::function<void (node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Value>)>) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0xf8fd43) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #28 0x1119693 in node::NodeMainInstance::Run() (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1119693) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #29 0x1058781 in node::Start(int, char**) (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0x1058781) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)
    #30 0x7a577362a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #31 0x7a577362a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #32 0xf8761d in _start (/home/alexhultman/.nvm/versions/node/v24.6.0/bin/node+0xf8761d) (BuildId: de7c8075f9f84e914a1af6157525571ea7e32e9b)

SUMMARY: AddressSanitizer: heap-buffer-overflow uWebSockets/src/ProxyParser.h:74 in uWS::ProxyParser::ProxyParser()
Shadow bytes around the buggy address:
  0x51200004d700: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x51200004d780: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51200004d800: fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa
  0x51200004d880: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x51200004d900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x51200004d980: 00 00 00 00 00 00 00 00 00 00 00 fa[fa]fa fa fa
  0x51200004da00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51200004da80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51200004db00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51200004db80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51200004dc00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==28036==ABORTING
```

**Comment by uNetworkingAB** [comment]
If you have other issues, please file them and use binaries-asan binaries to get more info on your segfaults
