### ISSUE TITLE
Performance of POST body parsing of HTTP server

### ISSUE THREAD

**Issue by JerryCauser** [uNetworking/uWebSockets.js#228]
Hello,

I got some strange bench results from `autocannon` when tested your lib for a simple HTTP-POST server. It greatly works until I pass a body to parse. Is that my mistake somewhere or maybe uws isn't well specified for that kind of job?

**OS**: `Mac OS 10.15.1`
**Node.js**: `v12.13.0`
**Lib**: `uWebSockets.js#v16.2.0`

```javascript
//create-post-server-uws.js
const uws = require('uWebSockets.js')

const MAX_BODY_SIZE = 2 ** 20 // 1MB

async function requestListener (req, res, handler) {
  res.writeHeader('Access-Control-Allow-Origin', '*')
  res.writeHeader('Access-Control-Allow-Headers', 'content-type')
  res.writeHeader('Content-Type', 'application/json')

  let aborted = false

  res.onAborted(() => {
    aborted = true
  })

  // let data = ''
  let data = Buffer.from([])

  res.onData(async (chunk, isLast) => {
    if (aborted) {
      return
    }

    data = Buffer.concat([data, Buffer.from(chunk)])
    // data += Buffer.from(chunk).toString('utf8')

    if (data.length > MAX_BODY_SIZE) {
      res.writeStatus('413 Payload Too Large')
      res.end(`{"code":413,"message":"Payload Too Large"}`)
      aborted = true

      return
    }

    if (isLast) {
      let params

      try {
        params = data.length ? JSON.parse(data) : {}
      } catch (e) {
        res.writeStatus('400 Invalid Request')
        res.end(`{"code":400,"message":"Invalid Request"}`)
      }

      if (!aborted) {
          if (result && typeof result === 'object') {
            res.end(JSON.stringify(result))
          } else {
            res.writeStatus('404 Not Found')
            res.end(`{"code":404,"message":"Not Found"}`)
          }
        }
      } catch (e) {
        if (e && e.statusCode) {
          res.writeStatus(e.statusCode)
          res.end(`{"code":${e.statusCode},"message":"${e.message}"}`)
        } else {
          res.writeStatus('500 Internal server error')
          res.end(`{"code":413,"message":"Payload Too Large"}`)
        }
      }
    }
  })
}

function methodNotAllowedResponse (res) {
  res.writeStatus('405 Method Not Allowed')
    .writeHeader('Allow', 'POST')
    .end(`{"code":405,"message":"Method Not Allowed"}`)
}

module.exports = (handler = () => console.log('Handler is not defined')) => {
  const server = uws.App()

  server.post('*', (res, req) => {
    requestListener(req, res, handler).catch(e => console.error(e))
  })
  server.get('*', methodNotAllowedResponse)

  return server
}
```
```javascript
const createApi = require('./create-post-server-uws')

const customServer = createApi(data => {
  return { hello: 'world' }
})

customServer.listen(8080, () => console.log('server started on port 8080'))
```

#### Result with body
```
$ autocannon -c 100 -p 100 -d 10 -m POST -b '{"a":1}' http://0.0.0.0:8080
Running 10s test @ http://0.0.0.0:8080
100 connections with 100 pipelining factor

┌─────────┬──────┬──────┬───────┬───────┬──────────┬──────────┬────────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg      │ Stdev    │ Max        │
├─────────┼──────┼──────┼───────┼───────┼──────────┼──────────┼────────────┤
│ Latency │ 0 ms │ 0 ms │ 56 ms │ 82 ms │ 13.01 ms │ 34.33 ms │ 3618.88 ms │
└─────────┴──────┴──────┴───────┴───────┴──────────┴──────────┴────────────┘
┌───────────┬─────┬──────┬────────┬────────┬────────┬─────────┬─────────┐
│ Stat      │ 1%  │ 2.5% │ 50%    │ 97.5%  │ Avg    │ Stdev   │ Min     │
├───────────┼─────┼──────┼────────┼────────┼────────┼─────────┼─────────┤
│ Req/Sec   │ 0   │ 0    │ 1253   │ 3683   │ 1655.6 │ 1489.25 │ 26      │
├───────────┼─────┼──────┼────────┼────────┼────────┼─────────┼─────────┤
│ Bytes/Sec │ 0 B │ 0 B  │ 231 kB │ 678 kB │ 305 kB │ 274 kB  │ 4.78 kB │
└───────────┴─────┴──────┴────────┴────────┴────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.

17k requests in 10.15s, 3.05 MB read
7k errors (0 timeouts)
```
#### Result without body
```
$ autocannon -c 100 -p 100 -d 10 -m POST http://0.0.0.0:8080
Running 10s test @ http://0.0.0.0:8080
100 connections with 100 pipelining factor

┌─────────┬──────┬──────┬───────┬───────┬─────────┬──────────┬───────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg     │ Stdev    │ Max       │
├─────────┼──────┼──────┼───────┼───────┼─────────┼──────────┼───────────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 45 ms │ 2.75 ms │ 28.89 ms │ 630.47 ms │
└─────────┴──────┴──────┴───────┴───────┴─────────┴──────────┴───────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬──────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg      │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼──────────┼─────────┼─────────┤
│ Req/Sec   │ 30607   │ 30607   │ 39903   │ 50015   │ 41142.23 │ 6397.84 │ 30600   │
├───────────┼─────────┼─────────┼─────────┼─────────┼──────────┼─────────┼─────────┤
│ Bytes/Sec │ 5.63 MB │ 5.63 MB │ 7.34 MB │ 9.21 MB │ 7.57 MB  │ 1.18 MB │ 5.63 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴──────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.

370k requests in 10.49s, 68.1 MB read
```

#### For comparison, the results of the same server based on the native node HTTP server
```
$ autocannon -c 100 -p 100 -d 10 -m POST -b '{"a":1}' http://0.0.0.0:8080
Running 10s test @ http://0.0.0.0:8080
100 connections with 100 pipelining factor

┌─────────┬──────┬──────┬───────┬───────┬─────────┬──────────┬────────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg     │ Stdev    │ Max        │
├─────────┼──────┼──────┼───────┼───────┼─────────┼──────────┼────────────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 88 ms │ 6.46 ms │ 65.71 ms │ 1385.44 ms │
└─────────┴──────┴──────┴───────┴───────┴─────────┴──────────┴────────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Req/Sec   │ 9583    │ 9583    │ 15039   │ 17039   │ 14840   │ 2133.04 │ 9578    │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Bytes/Sec │ 1.73 MB │ 1.73 MB │ 2.72 MB │ 3.08 MB │ 2.69 MB │ 387 kB  │ 1.73 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.

148k requests in 10.12s, 26.9 MB read
```

**Comment by alexhultman** [comment]
You're probably hitting a bug of some kind, see all those errors. Posted bodies should perform just like normal non-body requests.

Does autocannon send the body as chunked-transfer? This library does not support that yet, so maybe it just keeps closing the connection since it cannot parse it? I don't know, will test at some point.

**Comment by JerryCauser** [comment]
autocannon is coughing with 2 types of errors:
#### first one
```
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:770:11)
    at Socket._write (net.js:782:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at Client._doRequest (/Users/dev/projects/node_modules/autocannon/lib/httpClient.js:153:15)
    at HTTPParser.Client.parser.<computed> (/Users/dev/projects/node_modules/autocannon/lib/httpClient.js:103:10)
    at HTTPParser.nextRequest (/Users/dev/projects/node_modules/http-parser-js/http-parser.js:178:43) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```
#### second one
```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

I think autocannon uses default nodejs requests. I am not sure,  are they `chunked-transfer` or not.

**Comment by alexhultman** [comment]
The connection (s) is/are getting closed for some reason by some end.

**Comment by alexhultman** [comment]
autocannon is broken and sends invalid HTTP. The numbers for Node.js are really bad as well, since it closes the connection every time since autocannon sends two extra bytes at the end of the body, breaking the protocol. uWebSockets does not close the connection immediately, as it has a different parsing strategy. You have to test with a client that isn't garbage.

**Comment by JerryCauser** [comment]
Ok, thank you, I'll create an issue in autocannon repo.
Thank you for research
