### ISSUE TITLE
uWS is not compatible with your Node.js build

### ISSUE THREAD

**Issue by Lee182** [uNetworking/uWebSockets.js#313]
```
Error: Cannot find module './uws_win32_x64_80.node'
Require stack:
- \node_modules\.pnpm\github.com\uNetworking\uWebSockets.js\a24c50180536c1edbc112ba63cda7d07df1b4a93\node_modules\uWebSockets.js\uws.js
- \dist\main.js
- \node_modules\.pnpm\registry.npmjs.org\electron\9.0.0\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at \node_modules\.pnpm\github.com\uNetworking\uWebSockets.js\a24c50180536c1edbc112ba63cda7d07df1b4a93\node_modules\uWebSockets.js\uws.js:31:9
    at Object.<anonymous> (\node_modules\.pnpm\github.com\uNetworking\uWebSockets.js\a24c50180536c1edbc112ba63cda7d07df1b4a93\node_modules\uWebSockets.js\uws.js:33:3)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```
I'm using electron so the process version is different. anyway to build the src locally on my machine?

**Comment by alexhultman** [comment]
It's not for Electron. There is no such module version 80.
