### ISSUE TITLE
Docker alpine support

### ISSUE THREAD

**Issue by FerLuisxd** [uNetworking/uWebSockets.js#346]
Hello I've been trying to run this package with a docker image but when I try to run it I get this error:
```javascript
/src/node_modules/uWebSockets.js/uws.js:31
                throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
                ^

Error: This version of µWS is not compatible with your Node.js build:

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /src/node_modules/uWebSockets.js/uws_linux_x64_72.node)
    at /src/node_modules/uWebSockets.js/uws.js:31:9
    at Object.<anonymous> (/src/node_modules/uWebSockets.js/uws.js:33:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/src/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
```
This is my dockerfile
```docker
FROM node:lts-alpine
RUN apk --no-cache add git
WORKDIR /src
COPY package*.json ./

RUN npm install
COPY . .
EXPOSE 9001
CMD ["npm","start"]
```

**Comment by dalisoft** [comment]
@FerLuisxd See https://github.com/uNetworking/uWebSockets.js/issues/26 as this issue is **Pinned** in issues 😉

**Comment by alexhultman-2fa** [comment]
You are free to compile the sources for any platform you like, but the pre-compiled Linux binaries require glibc. Alpine is a muslc dist unlike 99% of Linux dists.
