### ISSUE TITLE
An error occurs on Node 18.12.1.

### ISSUE THREAD

**Issue by gmjung-platform** [uNetworking/uWebSockets.js#847]
The following error occurs on Node 18.12.1.

Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_darwin_arm64_108.node'
Require stack:
- /Volumes/Workspace/Developments/workspace_for_game/game-server-with-node.js/node_modules/uWebSockets.js/uws.js
- /Volumes/Workspace/Developments/workspace_for_game/game-server-with-node.js/node_modules/@colyseus/uwebsockets-transport/build/uWebSocketsTransport.js
- /Volumes/Workspace/Developments/workspace_for_game/game-server-with-node.js/node_modules/@colyseus/uwebsockets-transport/build/index.js
- /Volumes/Workspace/Developments/workspace_for_game/game-server-with-node.js/dist/Server.js
    at /Volumes/Workspace/Developments/workspace_for_game/game-server-with-node.js/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/Volumes/Workspace/Developments/workspace_for_game/game-server-with-node.js/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Volumes/Workspace/Developments/workspace_for_game/game-server-with-node.js/node_modules/@colyseus/uwebsockets-transport/build/uWebSocketsTransport.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Volumes/Workspace/Developments/workspace_for_game/game-server-with-node.js/node_modules/@colyseus/uwebsockets-transport/build/index.js:6:28)

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets.js/blob/binaries/uws_darwin_arm64_108.node

You're not really running this software, you're running some other version as part of some other NPM module.
