### ISSUE TITLE
Cannot find module './uws_linux_x64_108.node'

### ISSUE THREAD

**Issue by DrasticLp** [uNetworking/uWebSockets.js#852]
Hi,
I have this issue since trying to deploy on my linux server.
`Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_linux_x64_108.node'
Require stack:
- /home/debian/anymagik/server/node_modules/uWebSockets.js/uws.js
- /home/debian/anymagik/server/node_modules/@colyseus/uwebsockets-transport/build/uWebSocketsTransport.js
- /home/debian/anymagik/server/node_modules/@colyseus/uwebsockets-transport/build/index.js
- /home/debian/anymagik/server/src/server.ts
- /home/debian/anymagik/server/src/index.ts
    at /home/debian/anymagik/server/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/home/debian/anymagik/server/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._compile (/home/debian/anymagik/server/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-4798241668083143.js:114:20)
    at Object.nodeDevHook [as .js] (/home/debian/anymagik/server/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Function.Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/debian/anymagik/server/node_modules/@colyseus/uwebsockets-transport/build/uWebSocketsTransport.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._compile (/home/debian/anymagik/server/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-4798241668083143.js:114:20)
[ERROR] 16:29:36 Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_linux_x64_108.node'
Require stack:
- /home/debian/anymagik/server/node_modules/uWebSockets.js/uws.js
- /home/debian/anymagik/server/node_modules/@colyseus/uwebsockets-transport/build/uWebSocketsTransport.js
- /home/debian/anymagik/server/node_modules/@colyseus/uwebsockets-transport/build/index.js
- /home/debian/anymagik/server/src/server.ts
- /home/debian/anymagik/server/src/index.ts
`
I don't know why.
I used yarn (last version) and cleared all my node_modules before doing "yarn install"
I went to node_modules/uwebsockets.js there's the "uws_linux_x64_108.node"
Any idea ?

**Comment by e3dio** [comment]
Open issue with library you are using https://github.com/colyseus/colyseus tell them update uws.js version https://github.com/colyseus/colyseus/blob/master/packages/transport/uwebsockets-transport/package.json#L11

**Comment by e3dio** [comment]
You don't need that colyseus library get rid of that and code your app without it
