### ISSUE TITLE
HTTP Version Not Supported

### ISSUE THREAD

**Issue by yovanoc** [uNetworking/uWebSockets.js#990]
Hi,

Recently I started to observe some strange behaviors on my trpc adapter for uWebSockets:

Only when I stress test the server, he responds with a 505 HTTP Version Not Supported and I don't get why as it is not every time and the error don't seem appropriate. thanks for your help

```
TRPCClientError: Unexpected token '<', "<h1>HTTP V"... is not valid JSON
    at TRPCClientError.from (file:///Users/devchris/code/project/node_modules/.pnpm/@trpc+client@10.43.6_@trpc+server@10.43.6/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs:37:16)
    at file:///Users/devchris/code/project/node_modules/.pnpm/@trpc+client@10.43.6_@trpc+server@10.43.6/node_modules/@trpc/client/dist/httpUtils-f58ceda1.mjs:128:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: {
        aborted: false,
        rangeRequested: false,
        timingAllowPassed: true,
        requestIncludesCredentials: true,
        type: 'default',
        status: 505,
        timingInfo: {
          startTime: 739.0314900279045,
          redirectStartTime: 0,
          redirectEndTime: 0,
          postRedirectStartTime: 739.0314900279045,
          finalServiceWorkerStartTime: 0,
          finalNetworkResponseStartTime: 0,
          finalNetworkRequestStartTime: 0,
          endTime: 787.544527053833,
          encodedBodySize: 0,
          decodedBodySize: 0,
          finalConnectionTimingInfo: null
        },
        cacheState: '',
        statusText: 'HTTP Version Not Supported',
        headersList: HeadersList {
          cookies: null,
          [Symbol(headers map)]: Map(0) {},
          [Symbol(headers map sorted)]: null
        },
        urlList: [ URL {} ],
        body: {
          stream: ReadableStream {
            [Symbol(kType)]: 'ReadableStream',
            [Symbol(kState)]: [Object],
            [Symbol(nodejs.webstream.isClosedPromise)]: [Object],
            [Symbol(nodejs.webstream.controllerErrorFunction)]: [Function: bound error]
          }
        }
      },
      [Symbol(headers)]: Headers {
        [Symbol(headers list)]: HeadersList {
          cookies: null,
          [Symbol(headers map)]: Map(0) {},
          [Symbol(headers map sorted)]: null
        },
        [Symbol(guard)]: 'immutable',
        [Symbol(realm)]: null
      }
    }
  },
  shape: undefined,
  data: undefined,
  [cause]: SyntaxError: Unexpected token '<', "<h1>HTTP V"... is not valid JSON
      at JSON.parse (<anonymous>)
      at parseJSONFromBytes (node:internal/deps/undici/undici:4763:19)
      at successSteps (node:internal/deps/undici/undici:4734:27)
      at fullyReadBody (node:internal/deps/undici/undici:1447:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async specConsumeBody (node:internal/deps/undici/undici:4743:7)
}

Node.js v21.2.0
```

**Comment by uNetworkingAB** [comment]
Nobody can make anything out of this report. Post a reproducer of the issue using uWS.js only

**Comment by yovanoc** [comment]
Ok sorry. Was thinking reporting errors is good but will try to make a minimal reproduction.
